spring.config.import=optional:file:.env[.properties]

spring.application.name=patient
server.port=8082

# Connect to Supabase using Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# The Microservice Wall (Isolating the Patient data)
spring.jpa.properties.hibernate.default_schema=patient_schema

# JWT Secret (MUST match the Auth service exactly to verify tokens)
jwt.secret=${JWT_SECRET}

#File upload limits (for profile pictures, etc.)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Strictly limit and forcefully drop idle connections
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000