spring.config.import=optional:file:.env[.properties]

spring.application.name=symptom-checker
server.port=8088

ai.gemini.api-key=${GEMINI_API_KEY:}
ai.gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
ai.gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/models}

server.error.include-message=always
