apiVersion: v1
kind: Secret
metadata:
  name: medistream-secrets
  namespace: medistream
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0"
  DB_USERNAME: "postgres.nepfweteejxjuvwqgpek"
  DB_PASSWORD: "MediStream@Sliit123"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  GOOGLE_CLIENT_ID: ""
  STRIPE_API_KEY: "sk_test_demo_dummy_key_for_k8s"
  STRIPE_WEBHOOK_SECRET: "whsec_demo_dummy_key_for_k8s"
  GEMINI_API_KEY: ""
  SPRING_MAIL_USERNAME: "abishekjayasinghe944@gmail.com"
  SPRING_MAIL_PASSWORD: "kedcheitcukmnlxm"
  JITSI_JWT_SECRET: ""
