apiVersion: v1
kind: Secret
metadata:
  name: medistream-secrets
  namespace: medistream
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://<host>:<port>/<db>?sslmode=require&prepareThreshold=0"
  DB_USERNAME: "<db-username>"
  DB_PASSWORD: "<db-password>"
  JWT_SECRET: "<jwt-secret>"
  GOOGLE_CLIENT_ID: "<google-client-id>"
  STRIPE_API_KEY: "<stripe-api-key>"
  STRIPE_WEBHOOK_SECRET: "<stripe-webhook-secret>"
  GEMINI_API_KEY: "<gemini-api-key>"
  SPRING_MAIL_USERNAME: "<smtp-username>"
  SPRING_MAIL_PASSWORD: "<smtp-password>"
  JITSI_JWT_SECRET: "<jitsi-jwt-secret>"
