apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: medistream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: medistream-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: medistream-config
            - secretRef:
                name: medistream-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medistream
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
