apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: medistream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: medistream-notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: medistream-config
            - secretRef:
                name: medistream-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: medistream
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: ClusterIP
